// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadioAmateurHelper.Data;

#nullable disable

namespace RadioAmateurHelper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250608090000_AddPostOwnershipAndSiteSettings")]
    partial class AddPostOwnershipAndSiteSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");
#pragma warning restore 612, 618
        }
    }
}
